hackolade/Synapse

properties_pane/entity_level/entityLevelConfig.json

…aints and indexeses for same column

Constraints and indexes: add restriction to create constraints and table level indexes for same column

---

forward_engineering/configs/templates.js
forward_engineering/ddlProvider.js
forward_engineering/helpers/general.js
forward_engineering/helpers/keyHelper.js
properties_pane/entity_level/entityLevelConfig.json

https://hackolade.atlassian.net/browse/HCK-1317

add partition to options

---

forward_engineering/ddlProvider.js
reverse_engineering/databaseService/databaseService.js
reverse_engineering/reverseEngineeringService/helpers/index.js
reverse_engineering/reverseEngineeringService/helpers/reverseTablePartitions.js
reverse_engineering/reverseEngineeringService/reverseEngineeringService.js

https://hackolade.atlassian.net/browse/HCK-1360

add fe partitions from instance

---

adapter/0.1.35.json
package.json
properties_pane/entity_level/entityLevelConfig.json
properties_pane/field_level/fieldLevelConfig.json

https://hackolade.atlassian.net/browse/HCK-1255

enforce pk

---

polyglot/adapter.json
polyglot/convertAdapter.json

Added adapter config for converting identity and deriving autoincrement

HCK-3619: added adapter config for deriving autoincrement and converting identity

---

reverse_engineering/databaseService/databaseService.js
reverse_engineering/reverseEngineeringService/reverseEngineeringService.js

Added the same logging as in SQLServer.

HCK-4395: port logging enhancement from SQLServer plugin

---

forward_engineering/ddlProvider.js
forward_engineering/helpers/general.js
forward_engineering/helpers/indexHelper.js
reverse_engineering/databaseService/databaseService.js
reverse_engineering/reverseEngineeringService/helpers/handleType.js

This PR fixes missed logger argument issue [HCK-4541](https://hackolade.atlassian.net/browse/HCK-4541?atlOrigin=eyJpIjoiZmM3NTZiZmJhYmVkNDQ0MjhmYzViOTJiNzZkNzMyMmIiLCJwIjoiaiJ9)
It also removes unused and duplicated functions.
[HCK-4541]: https://hackolade.atlassian.net/browse/HCK-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HCK-4541: fix missed logger argument

---

reverse_engineering/databaseService/databaseService.js
reverse_engineering/databaseService/helpers/getNewConnectionClientByDb.js

* this should help decreasing the unknown problems, when the DB returns the following error: 
```operation timed out for an unknown reason```

HCK-5197: explicitly increased values for queries pool config

---

reverse_engineering/api.js

* added missing API method `parseConnectionString`. The following string will be resolved correctly:
```
jdbc:sqlserver://hackolade-test-ondemand.sql.azuresynapse.net:1433;database=master;user=sqladminuser@hackolade-test;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.sql.azuresynapse.net;loginTimeout=30;
```

HCK-5102: connection string parser

---

adapter/0.1.57.json

Re-validate container, entity, and field names after validation config update.

HCK-5271: add adapter to re-validate container, entity, and field names

---

forward_engineering/helpers/commentIfDeactivated.js
reverse_engineering/reverseEngineeringService/helpers/reorderTableRows.js
reverse_engineering/reverseEngineeringService/helpers/reverseTableColumn.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7072" title="HCK-7072" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7072</a>  Synapse - Fix sonar reports
</td></table>
<br />

HCK-7072: fix sonar issues

---

forward_engineering/ddlProvider.js
forward_engineering/utils/joinActivatedAndDeactivatedStatements.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8008" title="HCK-8008" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-8008</a>  [Synapse]: DDL script is not valid when the last attribute is commented in Table
</td></table>
<br />

HCK-8008: remove trailing comma before last deactivated column

---

reverse_engineering/connection_settings_modal/connectionSettingsModalConfig.json
reverse_engineering/databaseService/databaseService.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8467" title="HCK-8467" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-8467</a>  Add ClientId to Azure Active Directory (Username / Password)
</td></table>
<br />
Added clientId to Azure Active DIrectory connection modal config

Hck 8467 add client id to azure active directory username password

---

reverse_engineering/databaseService/helpers/errorService.js

You have no Jira task for this PR? Describe your changes here...
Improved logging in order to get the full stack trace of original (initial) error from library

HCK: improved logs to get the full stack trace from original (initial) RE error

---

forward_engineering/api.js
reverse_engineering/api.js
reverse_engineering/databaseService/databaseService.js
reverse_engineering/helpers/logInfo.js

HCK: enchacned logs

---

reverse_engineering/helpers/parseConnectionString.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8611" title="HCK-8611" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-8611</a>  SQL Server: error when trying to use "From connection string" parser
</td></table>
<br />
* handle the case when the Instance is in server param

HCK-8611: server Instance

---

reverse_engineering/databaseService/databaseService.js
reverse_engineering/databaseService/helpers/connection.js
reverse_engineering/helpers/logInfo.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8622" title="HCK-8622" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-8622</a>  Still unable to connect (logs in attachment)
</td></table>
<br />
Improved logs of hostname, username and authMethod. Refactored connection code

HCK-8622: refactored connection code and encahnced username, host and authmethod logs

---

reverse_engineering/databaseService/helpers/connection.js

Added default parameter for getTokenByAxiosMethod

HCK: added default parameter

---

reverse_engineering/databaseService/helpers/connection.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8742" title="HCK-8742" target="_blank"><img alt="Emergency" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10564?size=medium" />HCK-8742</a>  RE Synapse: Impossible to connect - Cannot read properties of undefined (reading 'authMethod')
</td></table>
<br />
Injected forgotten parameter

HCK-8742: inject forgotten argument

---

reverse_engineering/reverseEngineeringService/reverseEngineeringService.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8774" title="HCK-8774" target="_blank"><img alt="Emergency" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10564?size=medium" />HCK-8774</a>  [DHL] RE Synapse failed - Cannot read properties of undefined (reading 'some')
</td></table>
<br />
Interrupt table processing on absence of db table information

HCK-8774: interrupt table processing on absence of db table information

---

reverse_engineering/databaseService/databaseService.js
reverse_engineering/helpers/logInfo.js
reverse_engineering/helpers/parseConnectionString.js
reverse_engineering/reverseEngineeringService/reverseEngineeringService.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8721" title="HCK-8721" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-8721</a>  Assess if we can reuse the existing mechanism for reporting RE warnings to the end user
</td></table>
<br />
Improve RE robustness with handling not reversed entities

HCK-8721: improved partitions RE robustness

---

esbuild.package.js
package-lock.json
package.json

Updated bundling config to load lodash from the plugin node_modules

Hck lodash failing browser test fix
